// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbqhedfidgotnarfrcrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZicWhlZGZpZGdvdG5hcmZyY3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDg5NzYsImV4cCI6MjA2Njk4NDk3Nn0.NpwJ5fCMf7AV12_gbcBxRL_tPfKEtLX9uA24zc8OkaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});